"""Generate synthetic SD74 GDE input files for regression testing.

Produces realistic-looking but entirely fake data with the same column
schema as real SD74 GDE exports. Run this script once to regenerate
the snapshot input files (e.g. after a schema change):

    python tests/snapshots/generate_synthetic.py

The output (tests/snapshots/input/) is committed to git.
The golden output (tests/snapshots/output/) is regenerated by running:

    python -c "
    from pathlib import Path
    from src.main import main
    main('sd74myedbc', 'tests/snapshots/input', 'tests/snapshots/output')
    "
"""

import random
from pathlib import Path

OUTPUT_DIR = Path(__file__).parent / "input"
OUTPUT_DIR.mkdir(exist_ok=True)

random.seed(74)  # Reproducible

# ---------------------------------------------------------------------------
# Reference data
# ---------------------------------------------------------------------------

FIRST_NAMES = [
    "Emma",
    "Liam",
    "Olivia",
    "Noah",
    "Ava",
    "William",
    "Sophia",
    "James",
    "Isabella",
    "Oliver",
    "Mia",
    "Benjamin",
    "Charlotte",
    "Elijah",
    "Amelia",
    "Lucas",
    "Harper",
    "Mason",
    "Evelyn",
    "Logan",
]
LAST_NAMES = [
    "Smith",
    "Johnson",
    "Williams",
    "Brown",
    "Jones",
    "Garcia",
    "Miller",
    "Davis",
    "Wilson",
    "Taylor",
    "Anderson",
    "Thomas",
    "Jackson",
    "White",
    "Harris",
    "Martin",
    "Thompson",
    "Moore",
]

TEACHER_FIRST = ["Anne", "Brian", "Carol", "David", "Ellen", "Frank", "Grace", "Henry", "Irene", "Jason"]
TEACHER_LAST = ["Adams", "Baker", "Clark", "Dixon", "Evans", "Foster", "Grant", "Hill", "Irving", "Jones"]

SCHOOLS = [7474001, 7474005, 7474012, 7474018]
DOMAIN = "sd74.bc.ca"

GRADES = (
    ["K"] * 8
    + ["1"] * 8
    + ["2"] * 8
    + ["3"] * 8
    + ["4"] * 8
    + ["5"] * 8
    + ["6"] * 8
    + ["7"] * 8
    + ["8"] * 6
    + ["9"] * 6
    + ["10"] * 6
    + ["11"] * 5
    + ["12"] * 5
)

HOMEROOM_GRADES = {"K", "1", "2", "3", "4", "5", "6", "7"}

COURSES = [
    ("ENG08", "English 8"),
    ("ENG09", "English 9"),
    ("ENG10", "English 10"),
    ("ENG11", "English 11"),
    ("ENG12", "English 12"),
    ("MAT08", "Math 8"),
    ("MAT09", "Math 9"),
    ("MAT10", "Math 10"),
    ("SCI08", "Science 8"),
    ("SCI09", "Science 9"),
    ("SCI10", "Science 10"),
    ("PHE09", "PHE 9"),
    ("PHE10", "PHE 10"),
    ("SOC09", "Social Studies 9"),
    ("SOC10", "Social Studies 10"),
    ("ART10", "Art 10"),
    ("MUS10", "Music 10"),
    ("BUS11", "Business 11"),
    ("CS11", "Computer Science 11"),
    ("CS12", "Computer Science 12"),
]


def _pad(n: int, width: int = 7) -> str:
    return str(n).zfill(width)


def _dob(grade: str) -> str:
    age = {
        "K": 5,
        "1": 6,
        "2": 7,
        "3": 8,
        "4": 9,
        "5": 10,
        "6": 11,
        "7": 12,
        "8": 13,
        "9": 14,
        "10": 15,
        "11": 16,
        "12": 17,
    }.get(grade, 10)
    year = 2025 - age
    month = random.randint(1, 12)
    day = random.randint(1, 28)
    return f"{year}-{month:02d}-{day:02d}"


# ---------------------------------------------------------------------------
# Build entities
# ---------------------------------------------------------------------------

# Teachers: 10 teachers, distributed across schools
teachers = []
for i, (school, fn, ln) in enumerate(
    zip(
        [SCHOOLS[i % len(SCHOOLS)] for i in range(10)],
        TEACHER_FIRST,
        TEACHER_LAST,
    )
):
    teachers.append(
        {
            "teacher_id": f"T{_pad(1000 + i)}",
            "first": fn,
            "last": ln,
            "email": f"{ln.lower()}@{DOMAIN}",
            "school": school,
        }
    )

teacher_by_school: dict[int, list[dict]] = {}
for t in teachers:
    teacher_by_school.setdefault(t["school"], []).append(t)

# Students: ~100 students
students = []
for i in range(100):
    fn = random.choice(FIRST_NAMES)
    ln = random.choice(LAST_NAMES)
    grade = random.choice(GRADES)
    school = random.choice(SCHOOLS)
    # Pick a teacher for this student's school
    school_teachers = teacher_by_school.get(school, teachers[:2])
    teacher = random.choice(school_teachers)
    sid = _pad(2000000 + i)
    students.append(
        {
            "sid": sid,
            "first": fn,
            "last": ln,
            "grade": grade,
            "school": school,
            "teacher": teacher,
            "dob": _dob(grade),
            "homeroom": f"DIV {i % 12 + 1}",
            "usual_first": fn if random.random() > 0.7 else "",
            "usual_last": "",
        }
    )

# Parents: ~1.5 parents per student
parents = []
for s in students:
    count = random.randint(1, 2)
    for _ in range(count):
        pfn = random.choice(FIRST_NAMES)
        pln = s["last"]
        parents.append(
            {
                "school": s["school"],
                "sid": s["sid"],
                "student_last": s["last"],
                "student_first": s["first"],
                "grade": s["grade"],
                "homeroom": s["homeroom"],
                "surname": pln,
                "first": pfn,
                "email": f"{pfn.lower()}.{pln.lower()}@example.com",
            }
        )

# Schedule: homeroom + 3 subjects per secondary student
schedule_rows = []
mt_counter = [100000]


def _next_mt():
    mt_counter[0] += 1
    return f"MT{mt_counter[0]}"


for s in students:
    school_teachers = teacher_by_school.get(s["school"], teachers[:2])
    teacher = s["teacher"]

    if s["grade"] in HOMEROOM_GRADES:
        # Homeroom only
        schedule_rows.append(
            {
                "year": "2025/2026",
                "school": s["school"],
                "sid": s["sid"],
                "last": s["last"],
                "first": s["first"],
                "grade": s["grade"],
                "teacher_name": f"{teacher['last']} {teacher['first']}",
                "semester": "1",
                "course": f"HR-{s['grade']}",
                "how_taken": "Regular",
                "section": "A",
                "mt_id": _next_mt(),
                "teacher_id": teacher["teacher_id"],
                "room": "101",
                "schedule": "1-1",
            }
        )
    else:
        # 3–4 subject courses
        picked_courses = random.sample(COURSES, k=random.randint(3, 4))
        for course_code, _ in picked_courses:
            t = random.choice(school_teachers)
            schedule_rows.append(
                {
                    "year": "2025/2026",
                    "school": s["school"],
                    "sid": s["sid"],
                    "last": s["last"],
                    "first": s["first"],
                    "grade": s["grade"],
                    "teacher_name": f"{t['last']} {t['first']}",
                    "semester": random.choice(["1", "2"]),
                    "course": course_code,
                    "how_taken": "Regular",
                    "section": random.choice(["A", "B"]),
                    "mt_id": _next_mt(),
                    "teacher_id": t["teacher_id"],
                    "room": str(random.randint(100, 220)),
                    "schedule": f"{random.randint(1, 2)}-{random.randint(1, 5)}",
                }
            )

# Courses (unique set from schedule)
used_courses = {r["course"] for r in schedule_rows}
course_rows = []
for school in SCHOOLS:
    for code, title in COURSES:
        if code in used_courses:
            course_rows.append({"school": school, "code": code, "title": title})
    # Add homeroom course entries
    for grade_label in ["K", "1", "2", "3", "4", "5", "6", "7"]:
        course_rows.append(
            {
                "school": school,
                "code": f"HR-{grade_label}",
                "title": f"Homeroom {grade_label}",
            }
        )

# ClassInfoEnhanced: one row per schedule row (for blended detection)
class_rows = []
for r in schedule_rows[:50]:  # Subset for class info
    class_rows.append(
        {
            "school": r["school"],
            "course": r["course"],
            "teacher_id": r["teacher_id"],
            "primary": "Y",
            "section": r["section"],
            "semester": r["semester"],
            "term": "1",
            "day": str(random.randint(1, 2)),
            "period": str(random.randint(1, 5)),
            "mt_id": r["mt_id"],
            "class_id": f"CLS{mt_counter[0]}",
            "schedule_expr": r["schedule"],
            "max": "30",
            "unrotated": "",
        }
    )


# ---------------------------------------------------------------------------
# Write files
# ---------------------------------------------------------------------------


def _write(filename: str, header: str, rows: list[str]) -> None:
    path = OUTPUT_DIR / filename
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(header + "\n")
        for row in rows:
            f.write(row + "\n")
    print(f"  {filename}: {len(rows)} rows")


print("Generating synthetic SD74 snapshot input files...")

# StudentDemographicInformation.txt
_write(
    "StudentDemographicInformation.txt",
    "School number,Student number,Homeroom,Teacher name,PEN,User name,Legal surname,"
    "Legal first name,Legal middle name,Usual surname,Usual first name,Usual middle name,"
    "Street number,Street name,Apartment,Lot number,Concession number,Municipality,"
    "Province,Postal code,Mailing address,Date of birth,Proof of age,Gender,"
    "Graduation program,Phone number,Grade,Inclusive Education category,Aboriginal ancestry,"
    "First nations band,DIA,Home language,ESL,French immersion,Immigration status,"
    "Citizenship,Country of birth,Care card number,Admission reason,Admission date,"
    "Withdraw reason,Withdraw date,Previous school number,Previous school name,"
    "Home school number,Home school name,Counselor id,Counselor name,Case manager,"
    "Projected graduation year,Date graduated,Family courier indicator,AM / PM,Memo note,"
    "Teacher ID,Who has custody,CYIC or YAG,Agreement or order,Band of Origin,"
    "Send Email and Autodialer Calls?,Release of Info/Photos Outside of District?,"
    "Permission to Walk Home?,Allow Internet Access?,Field Trip Permission?,"
    "Release of Info to PAC",
    [
        f"{s['school']},{s['sid']},{s['homeroom']},{s['teacher']['last']} {s['teacher']['first']},"
        f"{''.join([str(random.randint(0, 9)) for _ in range(9)])},{s['first'].lower()}{s['sid']},"
        f"{s['last']},{s['first']},,{s['usual_last']},{s['usual_first']},,"
        f"{random.randint(100, 9999)},Maple St,,,,"
        f"Lillooet,BC,V0K1V0,,"
        f"{s['dob']},,{random.choice(['M', 'F'])},,"
        f"250-555-{random.randint(1000, 9999)},"
        f"{s['grade']},,,,,English,,,Canadian,Canada,"
        f"{_pad(random.randint(9000000000, 9999999999), 10)},,"
        f"2025-09-02,,,,{random.choice([7474001, ''])},{random.choice(['Gold Trail School', ''])},,"
        f",,,,2025,,,AM,,"
        f"{s['teacher']['teacher_id']},Both,,,,"
        f"Y,Y,Y,Y,Y,Y"
        for s in students
    ],
)

# studentcourseselection.txt
_write(
    "studentcourseselection.txt",
    "School Year,School Number,Student Number,Student Legal Last Name,"
    "Student Legal First Name,Grade,Teacher Name,Semester,Course Code,"
    "How Taken Description,Section,Master Timetable ID,DL Start Date,"
    "DL Course Active Date,DL Completion Date,Teacher ID,Room,Schedule",
    [
        f"{r['year']},{r['school']},{r['sid']},{r['last']},{r['first']},"
        f"{r['grade']},{r['teacher_name']},{r['semester']},{r['course']},"
        f"{r['how_taken']},{r['section']},{r['mt_id']},,,,"
        f"{r['teacher_id']},{r['room']},{r['schedule']}"
        for r in schedule_rows
    ],
)

# StaffInformation.txt
_write(
    "StaffInformation.txt",
    "School Number,User Name,Teaching Staff,Teacher Id,Name,Prefix,Last Name,First Name,Email Address",
    [
        f"{t['school']},{t['first'].lower()}{t['last'].lower()},"
        f"Y,{t['teacher_id']},"
        f"{t['last']} {t['first']},,"
        f"{t['last']},{t['first']},{t['email']}"
        for t in teachers
    ],
)

# ParentInformation.txt
_write(
    "ParentInformation.txt",
    "School Number,Student Number,Student Legal Last Name,Student Legal First Name,"
    "Grade,Homeroom,User Name,Surname,First Name,Prefix,Parent Type,"
    "Parent Type Description,Business Phone,Business Phone Extension,Home Phone,"
    "Cellular Phone,Email Address,Place of Employment,Apartment,Street Number,"
    "Street Name,Community,Postal Code,Rural Code,Postal Box,Lot Number,"
    "Concession Number,Mailing Address,Custody Status,Home Language,"
    "Living With Student,RR Number / PO Box",
    [
        f"{p['school']},{p['sid']},{p['student_last']},{p['student_first']},"
        f"{p['grade']},{p['homeroom']},{p['first'].lower()}{p['surname'].lower()},"
        f"{p['surname']},{p['first']},,"
        f"{'MO' if random.random() > 0.5 else 'FA'},Mother,,,,"
        f"250-555-{random.randint(1000, 9999)},"
        f"{p['email']},,,{random.randint(100, 999)},Pine Ave,"
        f"Lillooet,V0K1V0,,,,,,"
        f"Active,English,Y,"
        for p in parents
    ],
)

# CourseInformation.txt
_write(
    "CourseInformation.txt",
    "School Number,Department,Standard Course Department Category Code,"
    "Standard Course Department Category Description,Course Code,Course Type,"
    "Title,Course Description,Credit Value,Grade Level,Catalogue Description,"
    "Short Name,Course Number,Format,Course Length,Academic Level Code,"
    "Include in Honour Roll,Include in GPA,Non Standard,Exam,"
    "On Report Card Indicator,Career Prep Indicator,Vocational Indicator",
    [
        f"{c['school']},Core,,,"
        f"{c['code']},Regular,{c['title']},{c['title']} course,"
        f"4,{random.randint(8, 12)},{c['title']},"
        f"{c['code'][:3]},{random.randint(100, 999)},Classroom,Year,"
        f"Regular,Y,Y,N,Y,Y,N,N"
        for c in course_rows
    ],
)

# ClassInfoEnhanced.txt
_write(
    "ClassInfoEnhanced.txt",
    "School Number,Course Code,Teacher Id,Primary Teacher,Section Letter,"
    "Semester,Term,Day,Period,Master Timetable ID,Class Identifier,"
    "Schedule Expression,Max,Unrotated Schedule",
    [
        f"{c['school']},{c['course']},{c['teacher_id']},{c['primary']},"
        f"{c['section']},{c['semester']},{c['term']},{c['day']},{c['period']},"
        f"{c['mt_id']},{c['class_id']},{c['schedule_expr']},{c['max']},"
        f"{c['unrotated']}"
        for c in class_rows
    ],
)

print("Done. Now regenerate golden output with:")
print(
    "  python -c \"from src.main import main; main('sd74myedbc', 'tests/snapshots/input', 'tests/snapshots/output')\""
)
